version: '3.8'

services:
  mysql:
    container_name: 'tchat_real_time_mysql'
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --port=8001
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - type: volume
        source: tchat-real-time-db
        target: /var/lib/mysql
    ports:
      - "8001:8001"

  php:
    container_name: 'tchat_real_time_php'
    build:
      context: .
      dockerfile: ./docker/Dockerfile.php
    volumes:
      - type: volume
        source: tls
        target: /root/.symfony/certs
      - type: bind
        source: ./app
        target: /app
      - type: volume
        target: /app/vendor
    depends_on:
      - mysql
    ports:
      - "8000:8000"

  node-encore:
    container_name: 'tchat_real_time_node_encore'
    build:
      context: .
      dockerfile: ./docker/Dockerfile.encore.dev
    volumes:
      - type: volume
        source: tls
        target: /root/.symfony/certs
      - type: volume
        target: /app/node_modules
      - type: bind
        source: ./app
        target: /app
    depends_on:
      - php
    ports:
      - "8002:8002"

  node-ws:
    container_name: 'tchat_real_time_node_ws'
    build:
      context: .
      dockerfile: ./docker/Dockerfile.nodews.dev
    volumes:
      - type: volume
        source: tls
        target: /root/.symfony5/certs
      - type: volume
        target: /ws/node_modules
      - type: bind
        source: ./ws
        target: /app
    depends_on:
      - mysql
      - php
      - node-encore
    ports:
      - "8003:8003"

networks:
  dev:
    name: network_dev
    driver: bridge

volumes:
  tchat-real-time-db:
    external: true
  tls: